project/project/gallery/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'items/$', views.item_list, name='items'),
    url(r'items/(?P<object_id>\d+)/$', views.item_detail, name='items'),
    url(r'photos/(?P<object_id>\d+)/$', views.photo_detail, name='photos'),
]

project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gallery/', include('project.gallery.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/gallery/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import admin
from .items.fields import ThumbnailImageField
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('items', args=(self.id,))


class Photo(models.Model):
    item = models.ForeignKey(Item)
    title = models.CharField(max_length=100)
    image = ThumbnailImageField(upload_to='photos')
    caption = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return self.title

    def get_absolute_url(selfs):
        return reverse('photos', args=(selfs.id,))


class PhotoInLine(admin.StackedInline):
    model = Photo


class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInLine]


admin.site.register(Item, ItemAdmin)
admin.site.register(Photo)

project/project/gallery/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item, Photo


def home(request):
    return render(request, 'home.html', {'item_list': Item.objects.all()[:2]})


def item_list(request):
    return render(request, 'item_list.html', {'item_list': Item.objects.all()})


def item_detail(request, object_id):
    _item_detail = get_object_or_404(Item, id = object_id)
    return render(request, 'item_detail.html', {'item_detail': _item_detail})


def photo_detail(request, object_id):
    _photo_detail = get_object_or_404(Photo, id = object_id)
    return render(request, 'photo_detail.html', {'photo_detail': _photo_detail})

project/project/gallery/templates/base.html
<html>
    <head>
        <title>Gallery {% block title %} {% endblock %}</title>
        <style type="text/css">
            body {margin: 30px; font-family: sans-serif; background: #fff;}
            h1 {background: #ccf; padding: 20px;}
            h2 {background: #ddf; padding: 10px 20px;}
            h3 {background: #eef; padding: 5px 20px;}
            table {width: 100%}
            table th {text-align: left;}
        </style>
    </head>
    <body>
        <h1>Gallery</h1>
        {% block content %}{% endblock %}
    </body>
</html>

project/project/gallery/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h2>Welcome to the Gallery</h2>
<h3>Showcases</h3>
<table>
    <tr>
        {% for item in item_list %}
        <td>
            <a href="{{item.get_absolute_url}}"> <b>{{item.name}}</b><br/>
                {% if item.photo_set.count %}
                <img src="{{item.photo_set.all.0.image.thumb_url}}">
                {% else %}
                <span>No photo yet</span>
                {% endif %}
            </a>
        </td>
        {% endfor %}
    </tr>
</table>
<p><a href="{% url 'items' %}">View the full list</a></p>
{% endblock %}

project/project/gallery/templates/item_detail.html
{% extends 'base.html' %}
{% block title%}{{item_detail.name}}{% endblock %}
{% block content %}
<p><a href="{% url 'items' %}"> Back to full items list</a></p>
<h2>{{item_detail.name}}</h2>
<p>{{item_detail.description}}</p>
<h3>Photos</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Thumbnail</th>
        <th>Caption</th>
    </tr>
    {% for photo in item_detail.photo_set.all %}
    <tr>
        <td><i>{{photo.title}}</i></td>
        <td>
            <a href="{{photo.get_absolute_url}}">
                <img src="{{photo.image.thumb_url}}">
            </a>
        </td>
        <td>{{photo.caption}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

project/project/gallery/templates/item_list.html
{% extends 'base.html' %}
{% block title %}Item list{% endblock %}

{% block content %}
<p><a href="{% url 'home' %}">Back to main page</a></p>
<h2>Items</h2>
{% if item_list %}
<table>
    <tr>
        <th>Name</th>
        <th>Sample thumb</th>
        <th>Description</th>
    </tr>
    {% for item in item_list %}
    <tr>
        <td><i>{{item.name}}</i></td>
        <td>
            {% if item.photo_set.count %}
            <a href="{{item.get_absolute_url}}">
                <img src="{{item.photo_set.all.0.image.thumb_url}}">
            </a>
            {% else %}
            (No photo current uploadet)
            {% endif %}
        </td>
        <td>{{item.description}}</td>
    </tr>
    {% endfor%}
</table>
{% else %}
{% endif %}
{% endblock %}

project/project/gallery/templates/photo_detail.html
{% extends 'base.html' %}
{% block title %}{{photo_detail.name}} - {{photo_detail.title}}{% endblock %}
{% block content %}
<a href="{{photo_detail.item.get_absolute_url}}">item detail page</a>
<h2>{{photo_detail.item.name}} - {{photo_detail.title}}</h2>
<img src="{{photo_detail.image.url}}"/>
{% if photo_detail.caption %}
<p>{{photo_detail.caption}}</p>
{% endif %}
{% endblock %}